In [ ]:
# While loop 
# it loops till the condition is satisfy


In [2]:
error = 50.0
while error > 1:
    error = error / 4
    print(error)

12.5
3.125
0.78125


In [ ]:
# for loop

In [ ]:
fam = [1.73, 1.68, 1.71, 1.89]
for height in fam :
print(height)

In [3]:
# areas list
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Change for loop to use enumerate() and update print()
for index, a in enumerate(areas) :
    print(f'room {index}: {a}')

room 0: 11.25
room 1: 18.0
room 2: 20.0
room 3: 10.75
room 4: 9.5


In [ ]:
# loop over list of list

In [4]:
# house list of lists
house = [["hallway", 11.25], 
         ["kitchen", 18.0], 
         ["living room", 20.0], 
         ["bedroom", 10.75], 
         ["bathroom", 9.50]]
         
# Build a for loop from scratch
for name, area in house:
    print(f'the {name} is {area} sqm')

the hallway is 11.25 sqm
the kitchen is 18.0 sqm
the living room is 20.0 sqm
the bedroom is 10.75 sqm
the bathroom is 9.5 sqm


In [5]:
# loop over dictionary
world = { "afghanistan":30.55,
"albania":2.77,
"algeria":39.21 }
for key, value in world.items() :
    print(key + " -- " + str(value))

afghanistan -- 30.55
albania -- 2.77
algeria -- 39.21


In [ ]:
# loop over numpy array

In [7]:
# one-d array 
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2
for val in bmi :
    print(val)

21.85171572722109
20.97505668934241
21.750282138093777
24.74734749867025
21.44127836209856


In [9]:
# more than one d we should use nditer to loop on all elemnts of the array
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
meas = np.array([np_height, np_weight])
print(meas)

[[ 1.73  1.68  1.71  1.89  1.79]
 [65.4  59.2  63.6  88.4  68.7 ]]


In [10]:
# for meas we can not simply loop over meas but we should use np.nditer
for m in meas:
    print(m)
# not print all elements

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]


In [12]:
for m in np.nditer(meas):
    print(m)

1.73
1.68
1.71
1.89
1.79
65.4
59.2
63.6
88.4
68.7


## Recap
> Dictionary  : use methods
for key, val in my_dict.items() :  
> NumPy array : use functions
for val in np.nditer(my_array) :

In [41]:
import pandas as pd
url = 'https://raw.githubusercontent.com/nafis-git/Data_analysis_python/main/Python_Fundementals/data/cars.csv'
brics = pd.read_csv(url, index_col = 0)
brics

cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JPN           588          Japan         False
IN             18          India         False
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True

In [30]:
# when loop on a dataframe, it loops over columns name
for b in brics:
    print(b)

country
capital
area
population


In [31]:
# for iterating over rows of the dataframe we need to use iterrows method which result in a pandas series
for lab, row in brics.iterrows():
    print(lab)
    print(row)

BR
country         Brazil
capital       Brasilia
area             8.516
population       200.4
Name: BR, dtype: object
RU
country       Russia
capital       Moscow
area            17.1
population     143.5
Name: RU, dtype: object
IN
country           India
capital       New Delhi
area              3.286
population       1252.0
Name: IN, dtype: object
CH
country         China
capital       Beijing
area            9.597
population     1357.0
Name: CH, dtype: object
SA
country       South Africa
capital           Pretoria
area                 1.221
population           52.98
Name: SA, dtype: object


In [34]:
for lab, row in brics.iterrows():
    print(f'{lab}:captial is:{row.capital}')

BR:captial is:Brasilia
RU:captial is:Moscow
IN:captial is:New Delhi
CH:captial is:Beijing
SA:captial is:Pretoria


In [35]:
# lets add a column to the dataframe brics to have length of each country  name 
for lab,row in brics.iterrows():
    brics.loc[lab,'country_length'] = len(row['country'])
    

In [36]:
brics

country    capital    area  population  country_length
BR        Brazil   Brasilia   8.516      200.40             6.0
RU        Russia     Moscow  17.100      143.50             6.0
IN         India  New Delhi   3.286     1252.00             5.0
CH         China    Beijing   9.597     1357.00             5.0
SA  South Africa   Pretoria   1.221       52.98            12.0

In [40]:
"""however as in every step we creat a series it is not an efficient 
way to make the column, oner of the efficient way is to use apply method"""
brics = pd.read_csv('brics.csv', index_col = 0)
brics['country_length'] = brics['country'].apply(len)
brics

country    capital    area  population  country_length
BR        Brazil   Brasilia   8.516      200.40               6
RU        Russia     Moscow  17.100      143.50               6
IN         India  New Delhi   3.286     1252.00               5
CH         China    Beijing   9.597     1357.00               5
SA  South Africa   Pretoria   1.221       52.98              12